# Generated by Django 5.2 on 2025-05-02 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('universities', '0002_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.professor'),
        ),
    ]
