# Generated by Django 5.2 on 2025-05-02 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_professor'),
        ('universities', '0002_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.professor'),
        ),
    ]
