# Generated by Django 5.2 on 2025-05-02 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_disciplina'),
        ('universities', '0002_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.disciplina'),
        ),
    ]
