# Generated by Django 5.2 on 2025-05-02 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_usuario_alter_review_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='qualidade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
