# Generated by Django 5.2 on 2025-04-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professors',
            new_name='Professor',
        ),
    ]
