# Generated by Django 5.2 on 2025-05-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_rename_professors_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='departamento',
            field=models.CharField(default='Ciência da Computação', max_length=255),
        ),
    ]
