# Generated by Django 5.2 on 2025-05-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_professor_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('professores', models.ManyToManyField(related_name='universidades', to='professor.professor')),
            ],
        ),
    ]
