# Generated by Django 5.2 on 2025-05-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('carga_horaria', models.IntegerField()),
                ('universidades', models.ManyToManyField(blank=True, to='universities.universidade')),
            ],
        ),
    ]
